sudo: false

language: python

python: 3.7

install:
  - pip install -r requirements-dev.txt

script:
  - black .
  - flake8 .

notifications:
  email:
    recipients:
      - siddharthsingharoy@gmail.com
    on_success: always
    on_failure: never