# Generated by Django 3.1.1 on 2020-10-04 14:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('securityCode', models.IntegerField(blank=True, null=True)),
                ('timeCreated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reset Passwords',
            },
        ),
        migrations.CreateModel(
            name='Beaver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Cannot Specify')], default='Cannot Specify', max_length=1)),
                ('bio', models.TextField(blank=True, default='Hello everyone', help_text='Enter your profile bio')),
                ('date_of_birth', models.DateField()),
                ('profile_photo', models.ImageField(default='images/default/default_profile_img.jpg', help_text='Profile Photo', upload_to='images/profile/')),
                ('phone', models.BigIntegerField(validators=[django.core.validators.RegexValidator(message='Not a valid phone number', regex='^[1-9][0-9]{9}$')])),
                ('friends', models.ManyToManyField(blank=True, related_name='_beaver_friends_+', to='loginsignup.Beaver')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Beavers',
            },
        ),
    ]
