# Generated by Django 3.1.1 on 2020-10-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beaver',
            name='college',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='beaver',
            name='company',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='beaver',
            name='industry',
            field=models.TextField(null=True),
        ),
    ]
